micronaut:
  server:
    port: 8081
  application:
    name: wallet-backend
  openapi:
    enabled: true
    swagger-ui:
      enabled: true

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/wallet_db
    driverClassName: org.postgresql.Driver
    username: wallet_user
    password: wallet_pass
    dialect: POSTGRES

jpa.default.properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

liquibase:
  datasources:
    default:
      enabled: true
      change-log: classpath:db/changelog/db.changelog-master.yaml
